=== TAT-Hins/SEU_COMP_Server_SSM/WebTest/picture.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="CATALOG">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="picture"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="picture">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="basics"/>
				<xs:element ref="time"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="basics">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element ref="size"/>
				<xs:element ref="pixel"/>
				<xs:element ref="address"/>
			</xs:sequence>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="gif"/>
						<xs:enumeration value="jpg"/>
						<xs:enumeration value="png"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="time">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="create"/>
				<xs:element ref="modify"/>
				<xs:element ref="visit"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="size">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:maxExclusive value="20971520"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="pixel">
		<xs:complexType mixed="true">
			<xs:attribute name="height" type="xs:decimal" use="required"/>
			<xs:attribute name="width" type="xs:decimal" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="height">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0"/>
			<xs:maxInclusive value="10000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="width">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="0"/>
			<xs:maxInclusive value="10000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="address">
		<xs:complexType mixed="true"/>
	</xs:element>
	<xs:element name="create">
		<xs:complexType mixed="true">
			<xs:attribute name="year" type="xs:decimal" use="required"/>
			<xs:attribute name="month" type="xs:decimal" use="required"/>
			<xs:attribute name="day" type="xs:decimal" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="modify">
		<xs:complexType mixed="true">
			<xs:attribute name="year" type="xs:decimal" use="required"/>
			<xs:attribute name="month" type="xs:decimal" use="required"/>
			<xs:attribute name="day" type="xs:decimal" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="visit">
		<xs:complexType mixed="true">
			<xs:attribute name="year" type="xs:decimal" use="required"/>
			<xs:attribute name="month" type="xs:decimal" use="required"/>
			<xs:attribute name="day" type="xs:decimal" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="year">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="1970"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="month">
		<xs:restriction base="xs:decimal">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="12"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="day">
		<xs:restriction base="xs:decimal">
			<xs:minExclusive value="1"/>
			<xs:maxInclusive value="31"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== TAT-Hins/SEU_COMP_Server_SSM/WebTest/picture.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--DOCTYPE CATALOG SYSTEM "picture.dtd"-->
<CATALOG xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="picture.xsd">
	<picture name="00001">
		<basics type="jpg">
			<size>130460</size>
			<pixel height="600" width="900">600x900</pixel>
			<address>http://img.sccnn.com/bimg/341/00001.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00002">
		<basics type="jpg">
			<size>51781</size>
			<pixel height="600" width="450">600x450</pixel>
			<address>http://img.sccnn.com/bimg/341/00002.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00003">
		<basics type="jpg">
			<size>22750</size>
			<pixel height="600" width="400">600x400</pixel>
			<address>http://img.sccnn.com/bimg/341/00003.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00004">
		<basics type="jpg">
			<size>22706</size>
			<pixel height="600" width="429">600x429</pixel>
			<address>http://img.sccnn.com/bimg/341/00004.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00005">
		<basics type="jpg">
			<size>100519</size>
			<pixel height="600" width="570">600x570</pixel>
			<address>http://img.sccnn.com/bimg/341/00005.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00006">
		<basics type="jpg">
			<size>98219</size>
			<pixel height="600" width="793">600x793</pixel>
			<address>http://img.sccnn.com/bimg/341/00006.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00007">
		<basics type="jpg">
			<size>211471</size>
			<pixel height="600" width="790">600x790</pixel>
			<address>http://img.sccnn.com/bimg/341/00007.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00008">
		<basics type="jpg">
			<size>131458</size>
			<pixel height="600" width="900">600x900</pixel>
			<address>http://img.sccnn.com/bimg/341/00008.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00009">
		<basics type="jpg">
			<size>60856</size>
			<pixel height="600" width="350">600x350</pixel>
			<address>http://img.sccnn.com/bimg/341/00009.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00010">
		<basics type="jpg">
			<size>227551</size>
			<pixel height="600" width="843">600x843</pixel>
			<address>http://img.sccnn.com/bimg/341/00010.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00011">
		<basics type="jpg">
			<size>129070</size>
			<pixel height="600" width="900">600x900</pixel>
			<address>http://img.sccnn.com/bimg/341/00011.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00012">
		<basics type="jpg">
			<size>83083</size>
			<pixel height="600" width="878">600x878</pixel>
			<address>http://img.sccnn.com/bimg/341/00012.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00013">
		<basics type="jpg">
			<size>137157</size>
			<pixel height="600" width="829">600x829</pixel>
			<address>http://img.sccnn.com/bimg/341/00013.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00014">
		<basics type="jpg">
			<size>101848</size>
			<pixel height="600" width="785">600x785</pixel>
			<address>http://img.sccnn.com/bimg/341/00014.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00015">
		<basics type="jpg">
			<size>150903</size>
			<pixel height="600" width="841">600x841</pixel>
			<address>http://img.sccnn.com/bimg/341/00015.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00016">
		<basics type="jpg">
			<size>61531</size>
			<pixel height="600" width="600">600x600</pixel>
			<address>http://img.sccnn.com/bimg/341/00016.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00017">
		<basics type="jpg">
			<size>34124</size>
			<pixel height="600" width="403">600x403</pixel>
			<address>http://img.sccnn.com/bimg/341/00017.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00018">
		<basics type="jpg">
			<size>31177</size>
			<pixel height="600" width="405">600x405</pixel>
			<address>http://img.sccnn.com/bimg/341/00018.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00019">
		<basics type="jpg">
			<size>75080</size>
			<pixel height="600" width="546">600x546</pixel>
			<address>http://img.sccnn.com/bimg/341/00019.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
	<picture name="00020">
		<basics type="jpg">
			<size>40224</size>
			<pixel height="600" width="400">600x400</pixel>
			<address>http://img.sccnn.com/bimg/341/00020.jpg</address>
		</basics>
		<time>
			<create year="2018" month="3" day="13">2018-03-13</create>
			<modify year="2018" month="3" day="13">2018-03-13</modify>
			<visit year="2018" month="3" day="13">2018-03-13</visit>
		</time>
	</picture>
</CATALOG>
